name: Deploy

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: 18.10.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Config
        run: |
          git config --global init.defaultBranch "deploy"

      - uses: actions/checkout@v3

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v3
        id: ${{ env.NODE_VERSION }}-node-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-

      - name: Install packages
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          yarn install
        
      - name: Build
        run: |
          yarn build
          yarn seo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'