name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Config
        run: |
          git config --global init.defaultBranch "deploy"

      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: node-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Install packages
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
          yarn install
        
      - name: Build
        run: |
          yarn build
          yarn seo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'